### ISSUE TITLE
Docstrings Please

### ISSUE THREAD

**Issue by JoshOrndorff** [proof-media/rchain-notebook#1]
I'd like to understand the functions better. For example

https://github.com/proof-media/rchain-notebook/blob/a0e72dd25976c4289795c685f84f0372da9da262/src/casper.py#L24

**Comment by beetleman** [comment]
most of the code needs refactoring because during writing I think more about how to make it work than design. Today i will extract the whole lib with tests from proofs monorepo and after that, I can start adding doc string.

**Comment by beetleman** [comment]
`get_blocks` get GRPC channel as an argument (they call it channel in GRPC doc but ill rename it to connection) and return blocks, it works in the same way as `./rnode get-blocks`

**Comment by beetleman** [comment]
sadly I can't find free time to do it. but I'll do it i this week:D

**Comment by dckc** [comment]
no particular rush, I don't think. Thanks for the updates and thoughts.

**Comment by pdonorio** [comment]
Hi guys,
@beetleman has updated the code with type hints and better function names,
see the new repo:
https://github.com/proof-media/rchain-grpc

Installation is now possible via `pip` command:
```bash
pip install git+https://github.com/proof-media/rchain-grpc.git@master
```

I've updated the notebook image in this repo and the notebook for testing accordingly, see:
https://github.com/proof-media/rchain-notebook/blob/master/notebooks/rchain.ipynb

Would you test and let us know?
Any specific question please open issues in the other new repo.
